[package]
name = "near-dyn-configs"
version = "0.0.0"
publish = true
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/near/nearcore"
description = "Dynamic configure helpers for the near codebase"

[dependencies]
